export const IpcChannels = {
  workspaceBootstrap: "workspace.bootstrap",
  workspaceOpen: "workspace.open",
  workspaceCreate: "workspace.create",
  workspaceListRecent: "workspace.listRecent",
  workspaceSwitch: "workspace.switch",
  workspaceListTags: "workspace.listTags",
  workspaceClose: "workspace.close",
  fileListTree: "file.listTree",
  fileRead: "file.read",
  fileReadBinary: "file.readBinary",
  fileWriteAtomic: "file.writeAtomic",
  fileWriteBinaryAtomic: "file.writeBinaryAtomic",
  fileCreate: "file.create",
  fileRename: "file.rename",
  fileTrash: "file.trash",
  fileOpenExternal: "file.openExternal",
  fileRevealInFinder: "file.revealInFinder",
  externalFileConsumePendingOpen: "externalFile.consumePendingOpen",
  externalFileRead: "externalFile.read",
  externalFileWriteAtomic: "externalFile.writeAtomic",
  documentParse: "document.parse",
  searchQuery: "search.query",
  graphGetBacklinks: "graph.getBacklinks",
  attachmentImport: "attachment.import",
  attachmentPickImage: "attachment.pickImage",
  exportDocument: "export.document",
  clipboardWriteRich: "clipboard.writeRich",
  settingsGet: "settings.get",
  settingsSet: "settings.set",
  pluginsList: "plugins.list",
  pluginsSetEnabled: "plugins.setEnabled",
  pluginsAcceptPermissions: "plugins.acceptPermissions",
  pluginsRecordFailure: "plugins.recordFailure",
  extensionsSyncMenus: "extensions.syncMenus",
  diagnosticsOpenLogs: "diagnostics.openLogs"
} as const;

export type IpcChannel = (typeof IpcChannels)[keyof typeof IpcChannels];
